# -*- coding: utf-8 -*-
"""quantum_part1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AmwFAfsupa607A-aYN8TvaRFHdFfKGr7
"""

import numpy as np

# workspace
w = np.array([[1.0]])

# push qubit
def push(q):
    global w
    w = np.kron(w, q)

# apply X gate
def apply_X():
    global w
    X = np.array([[0,1],[1,0]])
    w[:] = (w.reshape(-1,2) @ X.T).reshape(1,-1)

# measure
def measure():
    global w
    probs = np.linalg.norm(w.reshape(-1,2), axis=0)**2
    probs = probs/np.sum(probs)
    return np.random.choice([0,1], p=probs)

# run demo
push([1,0])
push([3/5,4/5])
apply_X()

print("Workspace:", w)
print("Measurement:", measure())