# -*- coding: utf-8 -*-
"""gpu_part3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14viFu5UYQIc9q_WDriucmg8f2-lNg_3q
"""

import torch as pt

pt.autograd.set_grad_enabled(False)

# check device
if pt.cuda.is_available():
    device = pt.device("cuda")
    print("GPU available")
else:
    device = pt.device("cpu")
    print("Using CPU")

# simple "quantum workspace"
workspace = pt.tensor([[1.0]], device=device)

def push_qubit(weights):
    global workspace
    weights = pt.tensor(weights, device=device)
    workspace = pt.kron(workspace, weights)

# demo
push_qubit([1.0, 0.0])
push_qubit([0.6, 0.8])

print("Workspace:", workspace)