# -*- coding: utf-8 -*-
"""grover_part2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DI7jvjLCe1TwUppZKo3T5ucSpZUwNZtp
"""

import numpy as np

workspace = np.array([[1.0]])
namestack = []

X_gate = np.array([[0, 1],
                   [1, 0]], dtype=float)

H_gate = (1 / np.sqrt(2)) * np.array([[1, 1],
                                      [1, -1]], dtype=float)

Z_gate = np.diag([1] * 7 + [-1]).astype(float)  # 3-qubit controlled-Z


def reset_workspace():
    global workspace, namestack
    workspace = np.array([[1.0]])
    namestack = []


def pushQubit(name, weights):
    global workspace, namestack
    weights = np.array(weights, dtype=float)
    weights = weights / np.linalg.norm(weights)
    workspace = np.kron(workspace, weights)
    namestack.append(name)


def apply_single_qubit_gate(gate, qubit):
    global workspace, namestack
    idx = namestack.index(qubit)
    n = len(namestack)

    tensor = workspace.reshape([2] * n)
    tensor = np.moveaxis(tensor, idx, -1)
    tensor = tensor.reshape(-1, 2)
    tensor = tensor @ gate.T
    tensor = tensor.reshape([2] * n)
    tensor = np.moveaxis(tensor, -1, idx)
    workspace = tensor.reshape(1, -1)


def applyGate(gate, *qubits):
    global workspace
    if len(qubits) == 1:
        apply_single_qubit_gate(gate, qubits[0])
    else:
        workspace[:] = workspace @ gate.T


def zero_phaseOracle(qubits):
    for qubit in qubits:
        applyGate(X_gate, qubit)
    applyGate(Z_gate, *namestack)
    for qubit in qubits:
        applyGate(X_gate, qubit)


def sample_phaseOracle(qubits):
    applyGate(X_gate, qubits[1])
    applyGate(Z_gate, *namestack)
    applyGate(X_gate, qubits[1])


def probQubit(qubit):
    idx = namestack.index(qubit)
    n = len(namestack)
    tensor = workspace.reshape([2] * n)
    tensor = np.moveaxis(tensor, idx, -1)
    tensor = tensor.reshape(-1, 2)
    probs = np.linalg.norm(tensor, axis=0) ** 2
    return probs / np.sum(probs)


def measure_all():
    probs = np.abs(workspace.flatten()) ** 2
    probs = probs / np.sum(probs)
    state = np.random.choice(len(probs), p=probs)
    return format(state, f"0{len(namestack)}b")


def groverSearch(n, printProb=True):
    optimalTurns = int(np.pi / 4 * np.sqrt(2 ** n) - 1 / 2)
    qubits = list(range(n))

    for qubit in qubits:
        pushQubit(qubit, [1, 1])

    for _ in range(optimalTurns):
        sample_phaseOracle(qubits)
        for qubit in qubits:
            applyGate(H_gate, qubit)
        zero_phaseOracle(qubits)
        for qubit in qubits:
            applyGate(H_gate, qubit)
        if printProb:
            print(probQubit(qubits[0]))

    return measure_all()


if __name__ == "__main__":
    reset_workspace()
    result = groverSearch(3)
    print("Measured result:", result)